Change xml name
idpay/virtuemart pull request #7
Opened 2020-08-19 14:40 UTC by mnbp1371

2020-08-19 14:40 UTC, mnbp1371 commented
@vispamir

2020-08-20 12:05 UTC, vispamir requested changes

2020-08-20 12:05 UTC, vispamir commented on idpay_virtuemart/idpay_virtuemart.xml
>      <author>JMDMahdi, Vispa</author>
Add your name as developer:

Developer: JMDMahdi, vispa, mnbp1371 , Publisher: IDPay

2020-08-20 12:05 UTC, vispamir commented on idpay_virtuemart/idpay_virtuemart.xml
>      <author>JMDMahdi, Vispa</author>
Add Author mail to xml

2020-08-22 05:28 UTC, mnbp1371 commented
Add author name and email in xml file

@vispamir

2020-08-22 09:59 UTC, mnbp1371 commented
Change plugin name tag in xml file
@vispamir

2020-08-23 19:46 UTC, merged